/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.form;

import com.code.dao.MauDao;
import com.code.dao.SanPhamChiTietDao;
import com.code.dao.SizeDao;
import com.code.model.Mau;
import com.code.model.SanPham;
import com.code.model.SanPhamChiTiet;
import com.code.model.Size;
import com.edusys.utils.XImage;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phuck
 */
public class ChiTietSP extends javax.swing.JFrame {

    /**
     * Creates new form ChiTietSP
     */
    private List<Mau> listMau = new ArrayList<>();
    private List<Size> listSize = new ArrayList<>();
    private List<SanPhamChiTiet> listSPCT = new ArrayList<>();
    String text = "";

    public ChiTietSP() {
        initComponents();
        setLocationRelativeTo(this);
        colorBorder();
        loadTableMau();
        loadTableSize();
        loadComboBoxMau();
        loadComboBoxSize();
        setDefaultCloseOperation(ChiTietSP.DISPOSE_ON_CLOSE);
        loadTablChiTietSP();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jpnHinhAnh = new javax.swing.JPanel();
        jlbHinhAnh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboMau = new javax.swing.JComboBox<>();
        cboSize = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDanhSachSPCT = new javax.swing.JTable();
        jpnMauSize = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSachSize = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTenMau = new javax.swing.JTextField();
        txtMaMau = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTenSize = new javax.swing.JTextField();
        txtMaSize = new javax.swing.JLabel();
        btnThemMau = new javax.swing.JButton();
        btnThemSize = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDanhSachMau = new javax.swing.JTable();
        btnThemSPCT = new javax.swing.JButton();
        btnSuaSPCT = new javax.swing.JButton();
        btnXoaSPCT = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        txtMaSPCT = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        btnSuaSPCT1 = new javax.swing.JButton();

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jpnHinhAnh.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnHinhAnhLayout = new javax.swing.GroupLayout(jpnHinhAnh);
        jpnHinhAnh.setLayout(jpnHinhAnhLayout);
        jpnHinhAnhLayout.setHorizontalGroup(
            jpnHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHinhAnhLayout.createSequentialGroup()
                .addComponent(jlbHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        jpnHinhAnhLayout.setVerticalGroup(
            jpnHinhAnhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHinhAnhLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jlbHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Mã Sản Phẩm:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Giá:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tên Sản Phẩm:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Màu:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Size:");

        tblDanhSachSPCT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSachSPCT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachSPCTMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDanhSachSPCT);

        jpnMauSize.setBackground(new java.awt.Color(255, 255, 255));

        tblDanhSachSize.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSachSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachSizeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhSachSize);

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Mã Màu:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tên Màu:");

        txtMaMau.setForeground(new java.awt.Color(255, 255, 255));
        txtMaMau.setText("1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(4, 4, 4)
                        .addComponent(txtTenMau))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMaMau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaMau))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenMau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mã Size:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Tên Size:");

        txtMaSize.setForeground(new java.awt.Color(255, 255, 255));
        txtMaSize.setText("1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtTenSize, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(txtMaSize, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaSize))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        btnThemMau.setBackground(new java.awt.Color(153, 153, 255));
        btnThemMau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemMau.setForeground(new java.awt.Color(255, 255, 255));
        btnThemMau.setText("Thêm Màu");
        btnThemMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMauActionPerformed(evt);
            }
        });

        btnThemSize.setBackground(new java.awt.Color(153, 153, 255));
        btnThemSize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemSize.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSize.setText("Thêm Size");
        btnThemSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSizeActionPerformed(evt);
            }
        });

        tblDanhSachMau.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSachMau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMauMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblDanhSachMau);

        javax.swing.GroupLayout jpnMauSizeLayout = new javax.swing.GroupLayout(jpnMauSize);
        jpnMauSize.setLayout(jpnMauSizeLayout);
        jpnMauSizeLayout.setHorizontalGroup(
            jpnMauSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMauSizeLayout.createSequentialGroup()
                .addGroup(jpnMauSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnMauSizeLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnThemMau, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 101, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpnMauSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnMauSizeLayout.createSequentialGroup()
                        .addGroup(jpnMauSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnMauSizeLayout.createSequentialGroup()
                        .addComponent(btnThemSize, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        jpnMauSizeLayout.setVerticalGroup(
            jpnMauSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMauSizeLayout.createSequentialGroup()
                .addGroup(jpnMauSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jpnMauSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnMauSizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThemSize)
                    .addComponent(btnThemMau))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnThemSPCT.setBackground(new java.awt.Color(153, 153, 255));
        btnThemSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemSPCT.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSPCT.setText("Thêm ");
        btnThemSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPCTActionPerformed(evt);
            }
        });

        btnSuaSPCT.setBackground(new java.awt.Color(153, 153, 255));
        btnSuaSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaSPCT.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaSPCT.setText("Sửa ");
        btnSuaSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSPCTActionPerformed(evt);
            }
        });

        btnXoaSPCT.setBackground(new java.awt.Color(153, 153, 255));
        btnXoaSPCT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaSPCT.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaSPCT.setText("Xóa ");
        btnXoaSPCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPCTActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Số Lượng:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Mã Sản Phẩm CT:");

        txtMaSP.setEditable(false);

        txtMaSPCT.setEditable(false);
        txtMaSPCT.setText("1");

        txtTenSP.setEditable(false);

        txtGia.setEditable(false);

        btnSuaSPCT1.setBackground(new java.awt.Color(153, 153, 255));
        btnSuaSPCT1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSuaSPCT1.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaSPCT1.setText("Mở");
        btnSuaSPCT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSPCT1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(jpnMauSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(jScrollPane3)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jpnHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cboMau, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cboSize, 0, 281, Short.MAX_VALUE)
                    .addComponent(txtSoLuong)
                    .addComponent(txtMaSP)
                    .addComponent(txtMaSPCT)
                    .addComponent(txtTenSP)
                    .addComponent(txtGia))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(btnThemSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnSuaSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSuaSPCT1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnXoaSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtMaSPCT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemSPCT)
                    .addComponent(btnSuaSPCT)
                    .addComponent(btnXoaSPCT)
                    .addComponent(btnSuaSPCT1))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jpnMauSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSizeActionPerformed
        if (checkSize())
            insertSize();        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemSizeActionPerformed

    private void btnThemMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMauActionPerformed
        if (checkMau())
            insertMau();        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemMauActionPerformed

    private void tblDanhSachMauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMauMouseClicked
        fillToFormMau(tblDanhSachMau.getSelectedRow());        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachMauMouseClicked

    private void tblDanhSachSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachSizeMouseClicked
        fillToFormSize(tblDanhSachSize.getSelectedRow());        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachSizeMouseClicked

    private void btnThemSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPCTActionPerformed
        if (checkSPCT()) {
            insertCTSP();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemSPCTActionPerformed

    private void btnSuaSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSPCTActionPerformed
        if (checkSPCT()) {
            updateCTSP();
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnSuaSPCTActionPerformed

    private void btnXoaSPCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPCTActionPerformed
        deleteSanPham();        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaSPCTActionPerformed

    private void tblDanhSachSPCTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachSPCTMouseClicked
        fillToFormCTSP(tblDanhSachSPCT.getSelectedRow());        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachSPCTMouseClicked

    private void btnSuaSPCT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSPCT1ActionPerformed
        loadTablChiTietSP();       // TODO add your handling code here:
    }//GEN-LAST:event_btnSuaSPCT1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChiTietSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaSPCT;
    private javax.swing.JButton btnSuaSPCT1;
    private javax.swing.JButton btnThemMau;
    private javax.swing.JButton btnThemSPCT;
    private javax.swing.JButton btnThemSize;
    private javax.swing.JButton btnXoaSPCT;
    private javax.swing.JComboBox<String> cboMau;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel jlbHinhAnh;
    private javax.swing.JPanel jpnHinhAnh;
    private javax.swing.JPanel jpnMauSize;
    private javax.swing.JTable tblDanhSachMau;
    private javax.swing.JTable tblDanhSachSPCT;
    private javax.swing.JTable tblDanhSachSize;
    private javax.swing.JTextField txtGia;
    private javax.swing.JLabel txtMaMau;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtMaSPCT;
    private javax.swing.JLabel txtMaSize;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenMau;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTenSize;
    // End of variables declaration//GEN-END:variables

    public void fillToFormSPTOCT(JTextField txt1, JTextField txt2, JTextField txt3, String hinh) {
        txtMaSP.setText(txt1.getText());
        txtTenSP.setText(txt2.getText());
        txtGia.setText(txt3.getText());
        text = txt1.getText();

        if (hinh != null) {
            jlbHinhAnh.setToolTipText(hinh);
            ImageIcon icon = XImage.read(hinh);
            Image img = icon.getImage();
            Image sizeIcon = img.getScaledInstance(jlbHinhAnh.getWidth(), jlbHinhAnh.getHeight(), 0);
            ImageIcon newIcon = new ImageIcon(sizeIcon);
            jlbHinhAnh.setIcon(newIcon);
        } else {
            jlbHinhAnh.setToolTipText("");
            jlbHinhAnh.setIcon(null);
        }

    }

    public void colorBorder() {
        txtMaSP.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtMaSPCT.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtTenSP.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jpnHinhAnh.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtSoLuong.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtTenMau.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtTenSize.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtGia.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

// Màu
    public void loadTableMau() {
        String coulum[] = {"Mã Màu", "Mau"};
        DefaultTableModel model = new DefaultTableModel(coulum, 0);
        listMau = MauDao.getAllMau();
        for (Mau sv : listMau) {
            model.addRow(new Object[]{
                sv.getMaMau(),
                sv.getTenMau()
            });
        }
        tblDanhSachMau.setModel(model);
    }

    public Mau formToMau() {
        Mau sv = new Mau();
        sv.setMaMau(Integer.parseInt(txtMaMau.getText()));
        sv.setTenMau(txtTenMau.getText());
        return sv;
    }

    public void fillToFormMau(int index) {
        Mau sv = listMau.get(index);
        txtMaMau.setText("" + sv.getMaMau());
        txtTenMau.setText(sv.getTenMau());

    }

    public void loadComboBoxMau() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        listMau = MauDao.getAllMau();
        for (Mau sach : listMau) {
            model.addElement(sach.getTenMau());
        }
        cboMau.setModel(model);
    }

    public void insertMau() {
        Mau sv = formToMau();
        int rs = MauDao.insertMau(sv);
        if (rs > 0) {
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
            loadComboBoxMau();
            loadTableMau();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
        }
    }

    public boolean checkMau() {
        if (txtTenMau.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Không được để trống tên Màu!!");
            return false;
        }
        listMau = MauDao.getAllMau();
        for (Mau mau : listMau) {
            if (txtTenMau.getText().equalsIgnoreCase(mau.getTenMau())) {
                JOptionPane.showMessageDialog(this, "Màu đã tồn tại!!");
                return false;
            }
        }
        return true;
    }

    // Size
    public void loadTableSize() {
        String coulum[] = {"Mã Size", "Size"};
        DefaultTableModel model = new DefaultTableModel(coulum, 0);
        listSize = SizeDao.getAllSize();
        for (Size sv : listSize) {
            model.addRow(new Object[]{
                sv.getMaSize(),
                sv.getTenSize()

            });

        }
        tblDanhSachSize.setModel(model);
    }

    public void loadComboBoxSize() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        listSize = SizeDao.getAllSize();
        for (Size sach : listSize) {
            model.addElement(sach.getTenSize());
        }
        cboSize.setModel(model);
    }

    public Size formToSize() {
        Size sv = new Size();
        sv.setMaSize(Integer.parseInt(txtMaSize.getText()));
        sv.setTenSize(txtTenSize.getText());

        return sv;
    }

    public void fillToFormSize(int index) {

        Size sv = listSize.get(index);
        txtMaSize.setText("" + sv.getMaSize());
        txtTenSize.setText(sv.getTenSize());

    }

    public void insertSize() {
        Size sv = formToSize();
        int rs = SizeDao.insertSize(sv);
        if (rs > 0) {
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
            loadComboBoxSize();
            loadTableSize();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
        }
    }

    public boolean checkSize() {
        if (txtTenSize.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Không được để trống tên Size!!");
            return false;
        }
        listSize = SizeDao.getAllSize();
        for (Size mau : listSize) {
            if (txtTenSize.getText().equalsIgnoreCase(mau.getTenSize())) {
                JOptionPane.showMessageDialog(this, "Size đã tồn tại!!");
                return false;
            }
        }
        return true;
    }

    //Chi Tiết Sản Phẩm
    public void loadTablChiTietSP() {
        String coulum[] = {"Mã Sản Phẩm CT", "Mã SP", "Màu", "Size", "Giá", "Số Lượng"};
        DefaultTableModel model = new DefaultTableModel(coulum, 0);
        System.out.println("Mã" + txtMaSP.getText());
        listSPCT = SanPhamChiTietDao.getAllChiTietSP(txtMaSP.getText());
        System.out.println(text);
        for (SanPhamChiTiet sv : listSPCT) {
            model.addRow(new Object[]{
                sv.getMaSPCT(),
                sv.getMaSP(),
                sv.getTenMau(),
                sv.getTenSize(),
                sv.getDonGia(),
                sv.getSoLuong()
            });
        }
        tblDanhSachSPCT.setModel(model);
    }

    public SanPhamChiTiet formToSPCT() {
        SanPhamChiTiet sv = new SanPhamChiTiet();
        sv.setMaSPCT(Integer.parseInt(txtMaSPCT.getText()));
        sv.setMaSP(txtMaSP.getText());
        sv.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
        sv.setDonGia(Float.parseFloat(txtGia.getText()));

        listMau = MauDao.getAllMau();
        sv.setMaMau(listMau.get(cboMau.getSelectedIndex()).getMaMau());

        listSize = SizeDao.getAllSize();
        sv.setMaSize(listSize.get(cboSize.getSelectedIndex()).getMaSize());

        return sv;
    }

    public void fillToFormCTSP(int index) {

        SanPhamChiTiet sv = listSPCT.get(index);
        txtMaSP.setText(sv.getMaSP());
        txtMaSPCT.setText("" + sv.getMaSPCT());
        txtSoLuong.setText("" + sv.getSoLuong());
        txtGia.setText("" + sv.getDonGia());
        cboMau.setSelectedItem(sv.getTenMau());
        cboSize.setSelectedItem(sv.getTenSize());

    }

    public void insertCTSP() {
        SanPhamChiTiet sv = formToSPCT();
        int rs = SanPhamChiTietDao.insertCTSP(sv);
        if (rs > 0) {
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
            loadTablChiTietSP();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
        }
    }

    public void updateCTSP() {
        SanPhamChiTiet sv = formToSPCT();
        int rs = SanPhamChiTietDao.updateCTSP(sv);
        if (rs > 0) {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công");
            loadTablChiTietSP();
        } else {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thất Bại");
        }
    }

    public void deleteSanPham() {
        int ma = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa Sản Phẩm này không?");
        if (ma == 0) {
            int rs = SanPhamChiTietDao.deleteCTSP(Integer.parseInt(txtMaSPCT.getText()));
            if (rs > 0) {
                JOptionPane.showMessageDialog(this, "Xoá Thành Công");
                loadTablChiTietSP();
            } else {
                JOptionPane.showMessageDialog(this, "xóa Thất Bại");
            }
        } else {
            return;
        }
    }

    public boolean checkSPCT() {
        if (txtSoLuong.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Không được để trông!!");
            return false;
        }
        try {
            Integer sl = Integer.parseInt(txtSoLuong.getText());
            if (sl < 0) {
                JOptionPane.showMessageDialog(this, "Không được nhập số âm!!");
                return false;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số!!");
            return false;
        }
        return true;
    }

    public String text() {
        return text;
    }
}
