/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.raven.form;

import com.code.dao.NhaCungCapDao;
import com.code.model.NhaCungCap;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phuck
 */
public class QLNCC extends javax.swing.JFrame {

    /**
     * Creates new form QLNCC
     */
    private List<NhaCungCap> listNCC = new ArrayList<>();

    public QLNCC() {
        initComponents();
        loadTableNhaCC();
        colorBorder();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(QLNCC.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtEmail = new javax.swing.JTextField();
        txtMaNhaCC = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbTenNCC = new javax.swing.JLabel();
        jlbEmail = new javax.swing.JLabel();
        jlbDiaChi = new javax.swing.JLabel();
        jlbMaSoThue = new javax.swing.JLabel();
        jlb = new javax.swing.JLabel();
        jlbMaNhaCC = new javax.swing.JLabel();
        txtTenNCC = new javax.swing.JTextField();
        txtMaSoThue = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSanhNCC = new javax.swing.JTable();
        txtTimKiemNCC = new javax.swing.JTextField();
        jlb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtEmail.setBorder(null);
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtMaNhaCC.setBorder(null);
        txtMaNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhaCCActionPerformed(evt);
            }
        });

        txtDiaChi.setBorder(null);
        txtDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiaChiActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Mã Số Thuế:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Địa Chỉ:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Email:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Tên Nhà Cung Cấp: ");

        jlbTenNCC.setText("jLabel1");

        jlbEmail.setText("jLabel5");

        jlbDiaChi.setText("jLabel6");

        jlbMaSoThue.setText("jLabel8");

        jlb.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlb.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlb.setText("Mã Nhà Cung Cấp: ");

        jlbMaNhaCC.setText("jLabel1");

        txtTenNCC.setBorder(null);
        txtTenNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNCCActionPerformed(evt);
            }
        });

        txtMaSoThue.setBorder(null);
        txtMaSoThue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSoThueActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(153, 153, 255));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(153, 153, 255));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa ");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(153, 153, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSapXep.setBackground(new java.awt.Color(153, 153, 255));
        btnSapXep.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSapXep.setForeground(new java.awt.Color(255, 255, 255));
        btnSapXep.setText("Làm Mới ");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbTenNCC)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTenNCC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbMaNhaCC)
                                    .addComponent(txtMaNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbEmail)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaSoThue, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDiaChi)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbMaSoThue)
                                    .addComponent(jlbDiaChi))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(14, 14, 14))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb)
                    .addComponent(txtMaNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbMaNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTenNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbTenNCC)
                .addGap(16, 16, 16)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbEmail)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jlbDiaChi)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSoThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbMaSoThue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnSapXep)
                    .addComponent(btnXoa))
                .addGap(20, 20, 20))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblDanhSanhNCC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSanhNCC.setOpaque(false);
        tblDanhSanhNCC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSanhNCCMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSanhNCC);

        txtTimKiemNCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemNCCActionPerformed(evt);
            }
        });

        jlb1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlb1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jlb1.setText("Tìm Kiếm Tên NCC:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtTimKiemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb1)
                    .addComponent(txtTimKiemNCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblDanhSanhNCCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSanhNCCMouseClicked
        fillToFormNCC(tblDanhSanhNCC.getSelectedRow());        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSanhNCCMouseClicked

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtMaNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhaCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhaCCActionPerformed

    private void txtDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiaChiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiaChiActionPerformed

    private void txtTenNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNCCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNCCActionPerformed

    private void txtMaSoThueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSoThueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSoThueActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (check()) {
            if (checkMaTT()) {
                if (checkMSTTT()) {
                    if (checkEmail()) {
                        insertNhaCC();
                    }
                }
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (check()) {
            if (checkMaKOTT()) {
                if (checkEmail()) {
                    updateNhaCC();
                }
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        lamMoiNCC();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        deleteNhaCC();        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void txtTimKiemNCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemNCCActionPerformed
        timKiemNhaCC(txtTimKiemNCC.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemNCCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLNCC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLNCC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlb;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlbDiaChi;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbMaNhaCC;
    private javax.swing.JLabel jlbMaSoThue;
    private javax.swing.JLabel jlbTenNCC;
    private javax.swing.JTable tblDanhSanhNCC;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaNhaCC;
    private javax.swing.JTextField txtMaSoThue;
    private javax.swing.JTextField txtTenNCC;
    private javax.swing.JTextField txtTimKiemNCC;
    // End of variables declaration//GEN-END:variables

    public void loadTableNhaCC() {
        String coulum[] = {"Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Email", "Địa Chỉ", "Mã Số Thuế"};
        DefaultTableModel model = new DefaultTableModel(coulum, 0);
        listNCC = NhaCungCapDao.getAllNhaCungCap();
        for (NhaCungCap sv : listNCC) {
            model.addRow(new Object[]{
                sv.getMaNCC(),
                sv.getTenNCC(),
                sv.getEmail(),
                sv.getDiaChi(),
                sv.getMaSoThue()

            });
            tblDanhSanhNCC.setModel(model);
        }
    }

    public void lamMoiNCC() {
        txtMaNhaCC.setText("");
        txtTenNCC.setText("");
        txtEmail.setText("");
        txtDiaChi.setText("");
        txtMaSoThue.setText("");
        colorBorder();
    }

    public NhaCungCap formToNCC() {
        NhaCungCap ncc = new NhaCungCap();

        ncc.setMaNCC(txtMaNhaCC.getText());
        ncc.setTenNCC(txtTenNCC.getText());
        ncc.setEmail(txtEmail.getText());
        ncc.setDiaChi(txtDiaChi.getText());
        ncc.setMaSoThue(txtMaSoThue.getText());

        return ncc;
    }

    private boolean checkRong(JTextField txt, JLabel jlb, String Msg) {
        if (txt.getText().isBlank()) {
            txt.setBorder(BorderFactory.createLineBorder(Color.RED));
            jlb.setText(Msg);
            jlb.setForeground(Color.red);
            return false;
        }
        txt.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        jlb.setForeground(new Color(0, 0, 0, 0));
        return true;
    }

    public void fillToFormNCC(int index) {
        NhaCungCap ncc = listNCC.get(index);
        txtMaNhaCC.setText(ncc.getMaNCC());
        txtTenNCC.setText(ncc.getTenNCC());
        txtEmail.setText(ncc.getEmail());
        txtDiaChi.setText(ncc.getDiaChi());
        txtMaSoThue.setText(ncc.getMaSoThue());
    }

    public void insertNhaCC() {
        NhaCungCap sv = formToNCC();
        int rs = NhaCungCapDao.insertNhaCungCap(sv);
        if (rs > 0) {
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
            loadTableNhaCC();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
        }
    }

    public void updateNhaCC() {
        NhaCungCap sv = formToNCC();
        int rs = NhaCungCapDao.updateNhaCungCap(sv);
        if (rs > 0) {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công");
            loadTableNhaCC();
        } else {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thất Bại");
        }
    }

    public void deleteNhaCC() {
        int ma = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa Nhà Cung Cấp này không?");
        if (ma == 0) {
            int rs = NhaCungCapDao.deleteNhaCungCap(txtMaNhaCC.getText());
            if (rs > 0) {
                JOptionPane.showMessageDialog(this, "Xoá Thành Công");
                loadTableNhaCC();
            } else {
                JOptionPane.showMessageDialog(this, "xóa Thất Bại");
            }
        } else {
            return;
        }
    }

    public void colorBorder() {

        jlbMaNhaCC.setForeground(new Color(0, 0, 0, 0));
        jlbTenNCC.setForeground(new Color(0, 0, 0, 0));
        jlbEmail.setForeground(new Color(0, 0, 0, 0));
        jlbDiaChi.setForeground(new Color(0, 0, 0, 0));
        jlbMaSoThue.setForeground(new Color(0, 0, 0, 0));

        txtMaNhaCC.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        txtTenNCC.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        txtEmail.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        txtMaSoThue.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        txtDiaChi.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        txtTimKiemNCC.setBorder(BorderFactory.createLineBorder(Color.BLACK));

    }

    public void timKiemNhaCC(String ma) {
        listNCC = NhaCungCapDao.TimKiem(ma);
        String coulum[] = {"Mã Nhà Cung Cấp", "Tên Nhà Cung Cấp", "Email", "Địa Chỉ", "Mã Số Thuế"};
        DefaultTableModel model = new DefaultTableModel(coulum, 0);
        for (NhaCungCap sv : listNCC) {
            model.addRow(new Object[]{
                sv.getMaNCC(),
                sv.getTenNCC(),
                sv.getEmail(),
                sv.getDiaChi(),
                sv.getMaSoThue()

            });
            tblDanhSanhNCC.setModel(model);
        }
    }

    public boolean check() {
        //
        if (txtMaNhaCC.getText().isBlank()) {
            jlbMaNhaCC.setText("Mã Nhà Cung Cấp Không Được Để Trống!!");
            jlbMaNhaCC.setForeground(Color.red);
            return false;
        } else {
            jlbMaNhaCC.setForeground(new Color(0, 0, 0, 0));
        }
        //
        if (txtTenNCC.getText().isBlank()) {
            jlbTenNCC.setText("Tên Nhà Cung Cấp Không Được Để Trống!!");
            jlbTenNCC.setForeground(Color.red);
            return false;
        } else {
            jlbTenNCC.setForeground(new Color(0, 0, 0, 0));
        }
        //
        if (txtEmail.getText().isBlank()) {
            jlbEmail.setText("Email Nhà Cung Cấp Không Được Để Trống!!");
            jlbEmail.setForeground(Color.red);
            return false;
        } else {
            jlbEmail.setForeground(new Color(0, 0, 0, 0));
        }
        //
        if (txtDiaChi.getText().isBlank()) {
            jlbDiaChi.setText("Địa Chỉ Nhà Cung Cấp Không Được Để Trống!!");
            jlbDiaChi.setForeground(Color.red);
            return false;
        } else {
            jlbDiaChi.setForeground(new Color(0, 0, 0, 0));
        }
        //
        if (txtMaSoThue.getText().isBlank()) {
            jlbMaSoThue.setText("Mã Số Thuế Nhà Cung Cấp Không Được Để Trống!!");
            jlbMaSoThue.setForeground(Color.red);
            return false;
        } else {
            jlbMaSoThue.setForeground(new Color(0, 0, 0, 0));
        }
        return true;
    }

    public boolean checkMaTT() {
        listNCC = NhaCungCapDao.getAllNhaCungCap();
        for (NhaCungCap sanPham : listNCC) {
            if (txtMaNhaCC.getText().equals(sanPham.getMaNCC())) {
                jlbMaNhaCC.setText("Mã Nhà Cung Cấp Đã Tồn Tại!!");
                jlbMaNhaCC.setForeground(Color.red);
                return false;
            }
        }
        jlbMaNhaCC.setForeground(new Color(0, 0, 0, 0));
        return true;
    }

    public boolean checkMSTTT() {
        listNCC = NhaCungCapDao.getAllNhaCungCap();
        for (NhaCungCap sanPham : listNCC) {
            if (txtMaSoThue.getText().equals(sanPham.getMaSoThue())) {
                jlbMaSoThue.setText("Mã Nhà Cung Cấp Đã Tồn Tại!!");
                jlbMaSoThue.setForeground(Color.red);
                return false;
            }
        }
        jlbMaSoThue.setForeground(new Color(0, 0, 0, 0));
        return true;
    }

    public boolean checkMaKOTT() {
        listNCC = NhaCungCapDao.getAllNhaCungCap();
        for (NhaCungCap sanPham : listNCC) {
            if (txtMaNhaCC.getText().equals(sanPham.getMaNCC())) {
                jlbMaNhaCC.setForeground(new Color(0, 0, 0, 0));

                return true;
            }
        }
        jlbMaNhaCC.setText("Mã Nhà Cung Cấp Không Tồn Tại!!");
        jlbMaNhaCC.setForeground(Color.red);
        return false;
    }

    public boolean checkEmail() {
        String Remail = "^[a-zA-Z0-9]+@[a-z]+(\\.[a-z]+)+";
        if (txtEmail.getText().matches(Remail)) {

            jlbEmail.setForeground(new Color(0, 0, 0, 0));
            return true;
        } else {

            jlbEmail.setText("Email Không Đúng Định Dạng!!");
            jlbEmail.setForeground(Color.RED);
            return false;
        }
    }
}
