/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.code.dao.NhaCungCapDao;
import com.code.dao.NhapHangDao;
import com.code.model.CTNhapHang;
import com.code.model.NhaCungCap;
import com.code.model.NhapHang;
import com.code.model.NhapHang;
import com.edusys.utils.Auth;
import com.edusys.utils.XImage;
import java.awt.Color;
import java.awt.Image;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phuck
 */
public class QLNH extends javax.swing.JPanel {

    /**
     * Creates new form QLNH
     */
    private List<NhapHang> list = new ArrayList<>();
    private List<NhaCungCap> listNCC = new ArrayList<>();
    DecimalFormat decimalFormat = new DecimalFormat("#,###,##0.0");

    public QLNH() {
        initComponents();
        colorBorder();
        loadTableNhap();
        setNgayNhap();
        setNhapTenNV();
        loadComboBoxNhaCungCap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSachNhapHang = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtMaNhap = new javax.swing.JTextField();
        jlbMaNhap = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNgayNhap = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        cboNhaCC = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtTongSoLuong = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        btnThemSLSP = new javax.swing.JButton();
        btnThemNhaCC = new javax.swing.JButton();
        cboHTTT = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));

        tblDanhSachNhapHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSachNhapHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachNhapHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSachNhapHang);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Mã Nhập:");

        txtMaNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNhapActionPerformed(evt);
            }
        });

        jlbMaNhap.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Ngày Nhập:");

        txtNgayNhap.setEditable(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Mã Nhân Viên:");

        txtMaNV.setEditable(false);
        txtMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaNVActionPerformed(evt);
            }
        });

        cboNhaCC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Nhà Cung Cấp:");

        txtTongTien.setEditable(false);
        txtTongTien.setText("0");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tổng Tiền:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Số Lượng:");

        txtTongSoLuong.setEditable(false);
        txtTongSoLuong.setText("0");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Hình Thức Thanh Toán:");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sửa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(153, 153, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(153, 153, 255));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        btnThemSLSP.setBackground(new java.awt.Color(153, 153, 255));
        btnThemSLSP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemSLSP.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSLSP.setText("+");
        btnThemSLSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSLSPActionPerformed(evt);
            }
        });

        btnThemNhaCC.setBackground(new java.awt.Color(153, 153, 255));
        btnThemNhaCC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemNhaCC.setForeground(new java.awt.Color(255, 255, 255));
        btnThemNhaCC.setText("+");
        btnThemNhaCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhaCCActionPerformed(evt);
            }
        });

        cboHTTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tien Mat", "Chuyen Khoan" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboHTTT, 0, 338, Short.MAX_VALUE)
                            .addComponent(cboNhaCC, 0, 338, Short.MAX_VALUE)
                            .addComponent(jlbMaNhap)
                            .addComponent(txtMaNhap)
                            .addComponent(txtNgayNhap)
                            .addComponent(txtMaNV)
                            .addComponent(txtTongTien)
                            .addComponent(txtTongSoLuong))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnThemSLSP, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThemNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMaNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMaNhap)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtNgayNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboNhaCC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(btnThemNhaCC))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTongSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(btnThemSLSP))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cboHTTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi))
                .addContainerGap(138, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemSLSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSLSPActionPerformed
        QuanLyCTNH ct = new QuanLyCTNH();
        ct.setVisible(true);
        ct.fillMaNhap(txtMaNhap, txtTongSoLuong, txtTongTien);
    }//GEN-LAST:event_btnThemSLSPActionPerformed

    private void btnThemNhaCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhaCCActionPerformed
        new QLNCC().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnThemNhaCCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (check())
            if (checkMaTT())
                insertNhapHang();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (check())
            if (checkMaKoTT())
                updateNhapHang();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        deleteNhapHang();        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblDanhSachNhapHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachNhapHangMouseClicked
        fillToForm(tblDanhSachNhapHang.getSelectedRow());        // TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSachNhapHangMouseClicked

    private void txtMaNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNhapActionPerformed

    private void txtMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaNVActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamMoi();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnThemNhaCC;
    private javax.swing.JButton btnThemSLSP;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboHTTT;
    private javax.swing.JComboBox<String> cboNhaCC;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbMaNhap;
    private javax.swing.JTable tblDanhSachNhapHang;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaNhap;
    private javax.swing.JTextField txtNgayNhap;
    private javax.swing.JTextField txtTongSoLuong;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
public void colorBorder() {
        jlbMaNhap.setForeground(new Color(0, 0, 0, 0));
        txtMaNV.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtMaNhap.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtTongSoLuong.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtNgayNhap.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtTongTien.setBorder(BorderFactory.createLineBorder(Color.GRAY));
    }

    public void loadTableNhap() {
        String coulum[] = {"Mã Nhập", "Ngày Nhập", "Nhân Viên", "Nhà Cung Cấp", "Tổng Tiền", "Số Lượng", "Hình Thức TT"};
        DefaultTableModel model = new DefaultTableModel(coulum, 0);
        list = NhapHangDao.getAllNhapHang();
        for (NhapHang sv : list) {
            String tongTien = decimalFormat.format(sv.getTongTien());
            model.addRow(new Object[]{
                sv.getMaNhap(),
                sv.getNgayNhap(),
                sv.getMaNV(),
                sv.getMaNCC(),
                tongTien,
                sv.getTongSoLuong(),
                sv.getHinhThucTT()

            });
        }
        tblDanhSachNhapHang.setModel(model);
    }

    private void setNgayNhap() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ngayHienTai = dateFormat.format(new Date());
        txtNgayNhap.setText(ngayHienTai);
    }

    public void setNhapTenNV() {
        try {
            ImageIcon icon = XImage.read(XImage.img);
            System.out.println(XImage.img);
            Image img = icon.getImage();
            txtMaNV.setText(XImage.maNV);
        } catch (Exception e) {
        }
    }

    public void lamMoi() {
        txtMaNhap.setText("");
        txtMaNV.setText(Auth.user.getMaNV());
        setNgayNhap();
        txtTongSoLuong.setText("0");
        txtTongTien.setText("0.0");
    }

    public void loadComboBoxNhaCungCap() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        listNCC = NhaCungCapDao.getAllNhaCungCap();
        for (NhaCungCap sach : listNCC) {
            model.addElement(sach.getTenNCC());
        }
        cboNhaCC.setModel(model);
    }

    public NhapHang formToNH() {
        NhapHang sv = new NhapHang();
        sv.setMaNhap(txtMaNhap.getText());
        sv.setNgayNhap(txtNgayNhap.getText());
        sv.setTongTien(Float.parseFloat(txtTongTien.getText()));
        sv.setTongSoLuong(Integer.parseInt(txtTongSoLuong.getText()));
        sv.setMaNV(txtMaNV.getText());
        if (cboHTTT.getSelectedItem().equals("Tien Mat")) {
            sv.setHinhThucTT("Tien Mat");
        } else {
            sv.setHinhThucTT("Chuyen Khoan");
        }
        listNCC = NhaCungCapDao.getAllNhaCungCap();
        sv.setMaNCC(listNCC.get(cboNhaCC.getSelectedIndex()).getMaNCC());

        return sv;
    }

    public void fillToForm(int index) {
        NhapHang sv = list.get(index);

        txtMaNhap.setText(sv.getMaNhap());
        txtNgayNhap.setText(sv.getNgayNhap());
        txtMaNV.setText(sv.getMaNV());
        txtTongTien.setText(""+sv.getTongTien());
        cboNhaCC.setSelectedItem(sv.getMaNCC());
        txtTongSoLuong.setText("" + sv.getTongSoLuong());
        cboHTTT.setSelectedItem(sv.getHinhThucTT());
    }

    public void insertNhapHang() {
        NhapHang sv = formToNH();
        int rs = NhapHangDao.insertNhapHang(sv);
        if (rs > 0) {
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
            loadTableNhap();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
        }
    }

    public void updateNhapHang() {
        NhapHang sv = formToNH();
        int rs = NhapHangDao.updateNhapHang(sv);
        if (rs > 0) {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công");
            loadTableNhap();
        } else {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thất Bại");
        }
    }

    public void deleteNhapHang() {
        int ma = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa Hóa Đơn Nhập Hàng này không?");
        if (ma == 0) {
            int rs = NhapHangDao.deleteNhapHang(txtMaNhap.getText());
            if (rs > 0) {
                JOptionPane.showMessageDialog(this, "Xoá Thành Công");
                loadTableNhap();
            } else {
                JOptionPane.showMessageDialog(this, "xóa Thất Bại");
            }
        } else {
            return;
        }
    }

    public boolean check() {
        if (txtMaNhap.getText().isBlank()) {
            jlbMaNhap.setText("Không Được Để Trống Mã Nhập!!");
            jlbMaNhap.setForeground(Color.red);
            return false;
        } else {
            jlbMaNhap.setForeground(new Color(0, 0, 0, 0));
        }
        return true;
    }

    public boolean checkMaTT() {
        list = NhapHangDao.getAllNhapHang();
        for (NhapHang nhapHang : list) {
            if (txtMaNhap.getText().equals(nhapHang.getMaNhap())) {
                jlbMaNhap.setText("Mã Nhập Đã Tồn Tại!!");
                jlbMaNhap.setForeground(Color.red);
                return false;
            } else {
                jlbMaNhap.setForeground(new Color(0, 0, 0, 0));
            }
        }
        return true;
    }

    public boolean checkMaKoTT() {
        list = NhapHangDao.getAllNhapHang();
        for (NhapHang nhapHang : list) {
            if (txtMaNhap.getText().equals(nhapHang.getMaNhap())) {
                jlbMaNhap.setForeground(new Color(0, 0, 0, 0));
            }
            return true;
        }
        jlbMaNhap.setText("Mã Nhập Không Tồn Tại!!");
        jlbMaNhap.setForeground(Color.red);
        return false;
    }
}
