/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.code.dao.MauDao;
import com.code.dao.SanPhamChiTietDao;
import com.code.dao.SanPhamDao;
import com.code.dao.SizeDao;
import com.code.db.DBHelper;
import com.code.model.LoaiSanPham;
import com.code.model.Mau;
import com.code.model.SanPham;
import com.code.model.SanPhamChiTiet;
import com.code.model.Size;
import com.edusys.utils.XImage;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.*;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phuck
 */
public class QLSanPham extends javax.swing.JPanel {

    /**
     * Creates new form QLSanPham2
     */
    public QLSanPham() {
        initComponents();
        initComponents();
        loadComboBoxLoaiSP();
        loadTableSanPham();
        colorBorder();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblDanhSanhSP = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jpnHinh = new javax.swing.JPanel();
        jlbHinhAnh = new javax.swing.JLabel();
        txtTenSP = new javax.swing.JTextField();
        txtMaSP = new javax.swing.JTextField();
        txtGia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbMaSP = new javax.swing.JLabel();
        jlbTenSP = new javax.swing.JLabel();
        jlbGia = new javax.swing.JLabel();
        jlbLoai = new javax.swing.JLabel();
        jlbHinh = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSapXep = new javax.swing.JButton();
        btnLoai = new javax.swing.JButton();
        cboMau = new javax.swing.JComboBox<>();
        jlbMau = new javax.swing.JLabel();
        btnMau = new javax.swing.JButton();
        cboSize = new javax.swing.JComboBox<>();
        jlbSize = new javax.swing.JLabel();
        btnSize = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTimKiemSanPham = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblDanhSanhSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblDanhSanhSP.setOpaque(false);
        tblDanhSanhSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSanhSPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDanhSanhSP);

        jPanel3.setOpaque(false);

        jpnHinh.setBackground(new java.awt.Color(255, 255, 255));

        jlbHinhAnh.setBackground(new java.awt.Color(255, 255, 255));
        jlbHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHinhAnhMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnHinhLayout = new javax.swing.GroupLayout(jpnHinh);
        jpnHinh.setLayout(jpnHinhLayout);
        jpnHinhLayout.setHorizontalGroup(
            jpnHinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnHinhLayout.setVerticalGroup(
            jpnHinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHinhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHinhAnh, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtTenSP.setBorder(null);
        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        txtMaSP.setBorder(null);
        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        txtGia.setBorder(null);
        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Loại:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Giá:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tên Sản Phẩm:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Mã Sản Phẩm:");

        jlbMaSP.setText("jLabel1");

        jlbTenSP.setText("jLabel5");

        jlbGia.setText("jLabel6");

        jlbLoai.setText("jLabel8");

        jlbHinh.setText("jLabel1");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Hình Sản Phẩm: ");

        cboLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboLoaiMouseClicked(evt);
            }
        });
        cboLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(153, 153, 255));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(153, 153, 255));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa ");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(153, 153, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSapXep.setBackground(new java.awt.Color(153, 153, 255));
        btnSapXep.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSapXep.setForeground(new java.awt.Color(255, 255, 255));
        btnSapXep.setText("Làm Mới ");
        btnSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSapXepActionPerformed(evt);
            }
        });

        btnLoai.setBackground(new java.awt.Color(153, 153, 255));
        btnLoai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnLoai.setText("+");
        btnLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoaiActionPerformed(evt);
            }
        });

        cboMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboMauActionPerformed(evt);
            }
        });

        jlbMau.setText("jLabel8");

        btnMau.setBackground(new java.awt.Color(153, 153, 255));
        btnMau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMau.setForeground(new java.awt.Color(255, 255, 255));
        btnMau.setText("+");
        btnMau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMauActionPerformed(evt);
            }
        });

        jlbSize.setText("jLabel8");

        btnSize.setBackground(new java.awt.Color(153, 153, 255));
        btnSize.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSize.setForeground(new java.awt.Color(255, 255, 255));
        btnSize.setText("+");
        btnSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSizeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Màu:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("Size:");

        txtSoLuong.setEditable(false);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setText("Số Lượng:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jlbGia)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtGia)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenSP)
                            .addComponent(txtMaSP)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlbHinh)
                                    .addComponent(jlbTenSP)
                                    .addComponent(jlbMaSP))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(btnSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlbLoai)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnMau, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jlbMau)
                                    .addComponent(jlbSize)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(cboSize, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnSize, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtSoLuong))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(jpnHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpnHinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlbHinh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(7, 7, 7)
                .addComponent(jlbMaSP)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(7, 7, 7)
                .addComponent(jlbTenSP)
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbGia)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbLoai)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboMau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMau)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbMau)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSize)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbSize)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnSapXep)
                    .addComponent(btnSua)
                    .addComponent(btnThem))
                .addGap(16, 16, 16))
        );

        txtTimKiemSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemSanPhamActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tìm Kiếm Sản Phẩm:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtTimKiemSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 686, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jlbHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHinhAnhMouseClicked
        choAnh();        // TODO add your handling code here:
    }//GEN-LAST:event_jlbHinhAnhMouseClicked

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSPActionPerformed

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaSPActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (checkRong()) {
            if (checkMaTT()) {
                insertSanPham();
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (checkRong()) {
            if (checkMaKOTT()) {
                updateSinhVien();
            }
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        deleteSanPham();        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSapXepActionPerformed
        lamMoiNV();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSapXepActionPerformed

    private void btnSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSizeActionPerformed
        ChiTietSP ct = new ChiTietSP();
        ct.fillToFormSPTOCT(txtMaSP, txtTenSP, txtGia, hinh);
        ct.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnSizeActionPerformed

    private void tblDanhSanhSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSanhSPMouseClicked
        fillToForm(tblDanhSanhSP.getSelectedRow());
        fillSoLuong();// TODO add your handling code here:
    }//GEN-LAST:event_tblDanhSanhSPMouseClicked

    private void txtTimKiemSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemSanPhamActionPerformed
        timKiemSanPham();        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemSanPhamActionPerformed

    private void cboMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboMauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboMauActionPerformed

    private void btnMauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMauActionPerformed
        ChiTietSP ct = new ChiTietSP();
        ct.fillToFormSPTOCT(txtMaSP, txtTenSP, txtGia, hinh);
        ct.setVisible(true);
    }//GEN-LAST:event_btnMauActionPerformed

    private void btnLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoaiActionPerformed
        new QLLoaiSP().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoaiActionPerformed

    private void cboLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiActionPerformed
        
    }//GEN-LAST:event_cboLoaiActionPerformed

    private void cboLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboLoaiMouseClicked
        System.out.println(cboLoai.getSelectedItem());
        loadTableSanPhamLoai((String) cboLoai.getSelectedItem());// TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoai;
    private javax.swing.JButton btnMau;
    private javax.swing.JButton btnSapXep;
    private javax.swing.JButton btnSize;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cboLoai;
    private javax.swing.JComboBox<String> cboMau;
    private javax.swing.JComboBox<String> cboSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbGia;
    private javax.swing.JLabel jlbHinh;
    private javax.swing.JLabel jlbHinhAnh;
    private javax.swing.JLabel jlbLoai;
    private javax.swing.JLabel jlbMaSP;
    private javax.swing.JLabel jlbMau;
    private javax.swing.JLabel jlbSize;
    private javax.swing.JLabel jlbTenSP;
    private javax.swing.JPanel jpnHinh;
    private javax.swing.JTable tblDanhSanhSP;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiemSanPham;
    // End of variables declaration//GEN-END:variables

    private Map<String, Integer> loaiComboBoxMap;
    private List<SanPham> list = new ArrayList<>();
    private List<Mau> listMau = new ArrayList<>();
    private List<LoaiSanPham> listLSP = new ArrayList<>();
    private List<Size> listSize = new ArrayList<>();
    private List<String> listUrl = new ArrayList();
    String urlImage;
    String nameImage = "";
    String addFile = "D:\\finalTestSP.txt";
    private int currentIndex = 0;
    String hinh = "";
// Sản Phẩm

    public void loadTableSanPham() {
        String coulum[] = {"Mã Sản Phẩm", "Tên Sản Phẩm", "Giá", "Loại", "Hinh"};
        DefaultTableModel model = new DefaultTableModel(coulum, 0);
        list = SanPhamDao.getAllSanPham();
        for (SanPham sv : list) {
            model.addRow(new Object[]{
                sv.getMaSP(),
                sv.getTenSP(),
                sv.getGia(),
                sv.getMaLoai(),
                sv.getHinhAnh()

            });
            tblDanhSanhSP.setModel(model);
        }
    }
     public void loadTableSanPhamLoai(String ma) {
        String coulum[] = {"Mã Sản Phẩm", "Tên Sản Phẩm", "Giá", "Loại", "Hinh"};
        DefaultTableModel model = new DefaultTableModel(coulum, 0);
        list = SanPhamDao.TimKiemTheoLoai(ma);
        for (SanPham sv : list) {
            model.addRow(new Object[]{
                sv.getMaSP(),
                sv.getTenSP(),
                sv.getGia(),
                sv.getMaLoai(),
                sv.getHinhAnh()

            });
            tblDanhSanhSP.setModel(model);
        }
     }
       
    public int getAllSoLuong(String ma) {
        int soLuong = 0;
        try {
            Connection con = DBHelper.getDBConnection();
            String sql = "select sum(soLuong) from CHITIETSANPHAM where MASP ='" + ma + "'";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                soLuong = rs.getInt(1);
            }
        } catch (Exception e) {
            System.out.println("Lỗi Kết Nối");
            e.printStackTrace();
        }
        return soLuong;
    }

    public void fillSoLuong() {
        int soLuong = getAllSoLuong(txtMaSP.getText());
        txtSoLuong.setText(String.valueOf(soLuong));
    }

    public void colorBorder() {
        // Sản Phẩm
        jlbMaSP.setForeground(new Color(0, 0, 0, 0));
        jlbTenSP.setForeground(new Color(0, 0, 0, 0));
        jlbLoai.setForeground(new Color(0, 0, 0, 0));
        jlbGia.setForeground(new Color(0, 0, 0, 0));
        jlbHinh.setForeground(new Color(0, 0, 0, 0));
        jlbSize.setForeground(new Color(0, 0, 0, 0));
        jlbMau.setForeground(new Color(0, 0, 0, 0));

        txtSoLuong.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtMaSP.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtTenSP.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtGia.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        jpnHinh.setBorder(BorderFactory.createLineBorder(Color.GRAY));
        txtTimKiemSanPham.setBorder(BorderFactory.createLineBorder(Color.GRAY));

    }

    public void lamMoiNV() {
        txtMaSP.setText("");
        txtTenSP.setText("");
        txtGia.setText("");
        jlbHinhAnh.setIcon(null);
        colorBorder();
    }

    public void loadComboBoxLoaiSP() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        listLSP = SanPhamDao.getAllLoaiSP();
        for (LoaiSanPham sach : listLSP) {
            model.addElement(sach.getTenLoai());
        }
        cboLoai.setModel(model);
    }

    public void loadComboBoxMau() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        listMau = MauDao.TimKiem(txtMaSP.getText());
        for (Mau sach : listMau) {
            model.addElement(sach.getTenMau());
        }
        cboMau.setModel(model);
    }

    public void loadComboBoxSize() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.removeAllElements();
        listSize = SizeDao.TimKiem(txtMaSP.getText());
        for (Size sach : listSize) {
            model.addElement(sach.getTenSize());
        }
        cboSize.setModel(model);
    }

    public SanPham formToSV() {
        SanPham sv = new SanPham();
        sv.setMaSP(txtMaSP.getText());
        sv.setTenSP(txtTenSP.getText());
        sv.setGia(Float.parseFloat(txtGia.getText()));

        listLSP = SanPhamDao.getAllLoaiSP();
        sv.setMaLoai(listLSP.get(cboLoai.getSelectedIndex()).getMaLoai());
        sv.setHinhAnh(jlbHinhAnh.getToolTipText());
        return sv;
    }

    public void fillToForm(int index) {
        try {
            SanPham sv = list.get(index);
            txtMaSP.setText(sv.getMaSP());
            loadComboBoxMau();
            loadComboBoxSize();
            txtTenSP.setText(sv.getTenSP());
            txtGia.setText("" + sv.getGia());
            cboLoai.setSelectedItem(sv.getMaLoai());
            hinh = sv.getHinhAnh();
            if (sv.getHinhAnh() != null) {
                jlbHinhAnh.setToolTipText(sv.getHinhAnh());
                ImageIcon icon = XImage.read(sv.getHinhAnh());
                Image img = icon.getImage();
                Image sizeIcon = img.getScaledInstance(jlbHinhAnh.getWidth(), jlbHinhAnh.getHeight(), 0);
                ImageIcon newIcon = new ImageIcon(sizeIcon);
                jlbHinhAnh.setIcon(newIcon);
            } else {
                jlbHinhAnh.setToolTipText("");
                jlbHinhAnh.setIcon(null);
            }
        } catch (Exception e) {
            throw new RuntimeException();
        }
    }

    public void insertSanPham() {
        SanPham sv = formToSV();
        int rs = SanPhamDao.insertSanPham(sv);
        if (rs > 0) {
            JOptionPane.showMessageDialog(this, "Thêm Thành Công");
            loadTableSanPham();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm Thất Bại");
        }
    }

    public void updateSinhVien() {
        SanPham sv = formToSV();
        int rs = SanPhamDao.updateSanPham(sv);
        if (rs > 0) {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thành Công");
            loadTableSanPham();
        } else {
            JOptionPane.showMessageDialog(this, "Cập Nhật Thất Bại");
        }
    }

    public void deleteSanPham() {
        int ma = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa Sản Phẩm này không?");
        if (ma == 0) {
            int rs = SanPhamDao.deleteSanPham(txtMaSP.getText());
            if (rs > 0) {
                JOptionPane.showMessageDialog(this, "Xoá Thành Công");
                loadTableSanPham();
            } else {
                JOptionPane.showMessageDialog(this, "xóa Thất Bại");
            }
        } else {
            return;
        }
    }

    public void timKiemSanPham() {

        list = SanPhamDao.TimKiem(txtTimKiemSanPham.getText());
        String coulum[] = {"Mã Sản Phẩm", "Tên Sản Phẩm", "Giá", "Loại", "Hinh"};
        DefaultTableModel model = new DefaultTableModel(coulum, 0);
        for (SanPham sv : list) {
            model.addRow(new Object[]{
                sv.getMaSP(),
                sv.getTenSP(),
                sv.getGia(),
                sv.getMaLoai(),
                sv.getHinhAnh()

            });
            tblDanhSanhSP.setModel(model);
        }
    }

    void choAnh() {
        JFileChooser fileChooser = new JFileChooser();
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            ImageIcon icon = XImage.read(file.getName());
            XImage.save(file);
            Image img = icon.getImage();
            Image sizeIcon = img.getScaledInstance(jlbHinhAnh.getWidth(), jlbHinhAnh.getHeight(), 0);
            ImageIcon newIcon = new ImageIcon(sizeIcon);
            jlbHinhAnh.setIcon(newIcon);
            jlbHinhAnh.setToolTipText(file.getName());
        }
    }

    public boolean checkRong() {
        if (txtMaSP.getText().isBlank()) {
            jlbMaSP.setText("Mã Sản Phẩm Không Được Để Trống!!");
            jlbMaSP.setForeground(Color.red);
            return false;
        } else {
            jlbMaSP.setForeground(new Color(0, 0, 0, 0));
        }
        if (txtTenSP.getText().isBlank()) {
            jlbTenSP.setText("Tên Sản Phẩm Không Được Để Trống!!");
            jlbTenSP.setForeground(Color.red);
            return false;
        } else {
            jlbTenSP.setForeground(new Color(0, 0, 0, 0));
        }
        if (txtGia.getText().isBlank()) {
            jlbGia.setText("Giá Sản Phẩm Không Được Để Trống!!");
            jlbGia.setForeground(Color.red);
            return false;
        } else {
            jlbGia.setForeground(new Color(0, 0, 0, 0));
        }
        if (jlbHinhAnh.getIcon() == null) {
            jlbHinh.setText("Hình Sản Phẩm Không Được Để Trống!!");
            jlbHinh.setForeground(Color.red);
            return false;
        } else {
            jlbHinh.setForeground(new Color(0, 0, 0, 0));
        }

        try {
            float so = Float.parseFloat(txtGia.getText());
            if (so < 0) {
                jlbGia.setText("Không Được Để Số Âm!!");
                jlbGia.setForeground(Color.red);
                return false;
            }
        } catch (Exception e) {
            jlbGia.setText("Vui Lòng Nhập Số!!");
            jlbGia.setForeground(Color.red);
            return false;
        }
        colorBorder();
        return true;
    }

    public boolean checkMaTT() {
        list = SanPhamDao.getAllSanPham();
        for (SanPham sanPham : list) {
            if (txtMaSP.getText().equals(sanPham.getMaSP())) {
                jlbMaSP.setText("Mã Sản Phẩm Đã Tồn Tại!!");
                jlbMaSP.setForeground(Color.red);
                return false;
            }
        }
        jlbMaSP.setForeground(new Color(0, 0, 0, 0));
        return true;
    }

    public boolean checkMaKOTT() {
        list = SanPhamDao.getAllSanPham();
        for (SanPham sanPham : list) {
            if (txtMaSP.getText().equals(sanPham.getMaSP())) {
                jlbMaSP.setForeground(new Color(0, 0, 0, 0));

                return true;
            }
        }
        jlbMaSP.setText("Mã Sản Không Phẩm Đã Tồn Tại!!");
        jlbMaSP.setForeground(Color.red);
        return false;
    }
}
