/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.code.db;

import com.code.form2.*;
import com.code.db.*;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author phuck
 */
public class JpanelDangNhap extends javax.swing.JPanel {

    /**
     * Creates new form JpanelDangNhap
     */
    private int cornerRadius;
    public JpanelDangNhap() {
        initComponents();
        this.cornerRadius = cornerRadius;
        setOpaque(false); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
 @Override

    protected void paintComponent(Graphics g) {
        super.paintComponent(g);

        // Ép kiểu đối tượng Graphics thành Graphics2D để sử dụng các phương thức mở rộng
        Graphics2D g2d = (Graphics2D) g;

        int arcWidth = 20; // Độ cong theo chiều ngang
        int arcHeight = 20; // Độ cong theo chiều dọc

        // Vẽ hình chữ nhật có góc cong
        RoundRectangle2D roundedRectangle = new RoundRectangle2D.Float(50, 50, getWidth() - 100, getHeight() - 100, arcWidth, arcHeight);
        g2d.setColor(Color.WHITE);
        g2d.fill(roundedRectangle);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
