/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.code.form2;

import com.code.dao.NhanVienDao;
import com.code.model.NhanVien;
import com.edusys.utils.Auth;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author phuck
 */
public class DMK extends javax.swing.JPanel {

    /**
     * Creates new form DMK
     */
    public DMK() {
        initComponents();
        txtMatKhauCu.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        txtMatKhauMoi.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        txtXacNhan.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        lblMatKhauCu.setForeground(new Color(0, 0, 0, 0));
        lblMatKhauMoi.setForeground(new Color(0, 0, 0, 0));
        lblXacNhan.setForeground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelDangNhap2 = new com.code.db.JpanelDangNhap();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        lblMatKhauCu = new javax.swing.JLabel();
        lblMatKhauMoi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        lblXacNhan = new javax.swing.JLabel();
        txtMatKhauCu = new javax.swing.JPasswordField();
        txtXacNhan = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoUser.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Đổi Mật Khẩu");

        btnXacNhan.setBackground(new java.awt.Color(204, 51, 255));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnLamMoi.setBackground(new java.awt.Color(204, 51, 255));
        btnLamMoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        btnLamMoi.setText("Làm Mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        lblMatKhauCu.setForeground(new java.awt.Color(255, 0, 0));
        lblMatKhauCu.setText("Mật Khẩu Cũ Không Đúng!!");

        lblMatKhauMoi.setForeground(new java.awt.Color(255, 0, 0));
        lblMatKhauMoi.setText("Mật Khẩu Mới Trùng Với Mật Khẩu Cũ!!");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Nhập Mật Khẩu Cũ:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Nhập Mật Khẩu Mới:");

        txtMatKhauMoi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Xác Nhận Mật Khẩu:");

        lblXacNhan.setForeground(new java.awt.Color(255, 0, 0));
        lblXacNhan.setText("Xác Nhận Mật Khẩu Không Giống!!");

        txtMatKhauCu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        txtXacNhan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jpanelDangNhap2Layout = new javax.swing.GroupLayout(jpanelDangNhap2);
        jpanelDangNhap2.setLayout(jpanelDangNhap2Layout);
        jpanelDangNhap2Layout.setHorizontalGroup(
            jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(24, 24, 24)
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMatKhauMoi)
                            .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                                .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMatKhauCu)
                                    .addComponent(lblMatKhauMoi))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtMatKhauCu)))
                    .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblXacNhan))
                            .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txtXacNhan)))))
                .addGap(91, 91, 91))
        );
        jpanelDangNhap2Layout.setVerticalGroup(
            jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMatKhauCu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMatKhauMoi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblXacNhan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXacNhan)
                            .addComponent(btnLamMoi))))
                .addGap(0, 119, Short.MAX_VALUE))
        );

        add(jpanelDangNhap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 770, 490));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhNen.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 790));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        doiMatKhau();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        lamMoi();       // TODO add your handling code here:
    }//GEN-LAST:event_btnLamMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private com.code.db.JpanelDangNhap jpanelDangNhap2;
    private javax.swing.JLabel lblMatKhauCu;
    private javax.swing.JLabel lblMatKhauMoi;
    private javax.swing.JLabel lblXacNhan;
    private javax.swing.JPasswordField txtMatKhauCu;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtXacNhan;
    // End of variables declaration//GEN-END:variables
NhanVienDao dao = new NhanVienDao();
    List<NhanVien> listNV = dao.getAllNhanVien();

    public void lamMoi() {
        txtMatKhauCu.setText("");
        txtMatKhauMoi.setText("");
        txtXacNhan.setText("");
    }

    public void showLoi(JComponent lbl, JComponent txt, String loi) {
        ((JLabel) lbl).setText(loi);
        ((JLabel) lbl).setForeground(Color.RED);
        ((JTextField) txt).setBorder(BorderFactory.createLineBorder(Color.RED));
//              ((JLabel) lbl).setVisible(true);
    }

    public void offLoi(JComponent lbl, JComponent txt, String loi) {
        ((JLabel) lbl).setText(loi);
        ((JLabel) lbl).setForeground(Color.BLACK);
        ((JTextField) txt).setBorder(BorderFactory.createLineBorder(Color.BLACK));
//           ((JLabel) lbl).setVisible(false);
    }

    public boolean checkMK() {
        for (NhanVien nhanVien : listNV) {
            if (Auth.user.getMaNV().equalsIgnoreCase(nhanVien.getMaNV()) && dao.getMd5(txtMatKhauCu.getText().trim()).equals(nhanVien.getMatKhau())) {
                return true;
            }

        }
        return false;
    }

    public boolean checkNull() {
        if (txtMatKhauCu.getText().trim().equals("")) {
            showLoi(lblMatKhauCu, txtMatKhauCu, "Mật khẩu cũ không được để trống");
            return false;
        } else {
            offLoi(lblMatKhauCu, txtMatKhauCu, " ");
        }
        if (txtMatKhauMoi.getText().trim().equals("")) {
            showLoi(lblMatKhauMoi, txtMatKhauMoi, "Mật khẩu mới không được để trống");
            return false;
        } else {
            offLoi(lblMatKhauMoi, txtMatKhauMoi, " ");
        }
        if (txtXacNhan.getText().trim().equals("")) {
            showLoi(lblXacNhan, txtXacNhan, "Xác nhận mật khẩu mới không được để trống");
            return false;
        } else {
            offLoi(lblXacNhan, txtXacNhan, " ");
        }
        if (!checkMK()) {
            showLoi(lblMatKhauCu, txtMatKhauCu, "Mật khẩu cũ không đúng");
            return false;
        } else {
            offLoi(lblMatKhauCu, txtMatKhauCu, " ");
        }
        if (!txtMatKhauMoi.getText().trim().equals(txtXacNhan.getText().trim())) {
            showLoi(lblXacNhan, txtXacNhan, "Xác nhận mật khẩu không đúng");
            return false;
        } else {
            offLoi(lblXacNhan, txtXacNhan, " ");
        }
        return true;
    }

    public void doiMatKhau() {
        if (checkNull()) {
            NhanVien nv = new NhanVien();
//            System.out.println(Auth.user.getMaNV());
            System.out.println(txtXacNhan.getText().trim());
            nv.setMaNV(Auth.user.getMaNV());
            nv.setMatKhau(dao.getMd5(txtXacNhan.getText().trim()));
            dao.updateMK(nv);
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công");
            lamMoi();
        }
    }
    
}
