/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.code.form2;

import com.code.dao.NhanVienDao;
import com.code.model.NhanVien;
import java.awt.Color;
import java.util.List;
import java.util.Properties;
import java.util.Random;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;

/**
 *
 * @author phuck
 */
public class QuenMatKhau1 extends javax.swing.JDialog {

    /**
     * Creates new form QuenMatKhau1
     */
    String maOtp = "";

    public QuenMatKhau1(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
        jlbEmail.setForeground(new Color(0, 0, 0, 0));
        jlbMaOTP.setForeground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelDangNhap2 = new com.code.db.JpanelDangNhap();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnXacNhan = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jlbEmail = new javax.swing.JLabel();
        jlbMaOTP = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnGuiEmail = new javax.swing.JButton();
        txtMaOTP = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LogoUser.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Quên Mật Khẩu");

        txtEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });

        btnXacNhan.setBackground(new java.awt.Color(204, 51, 255));
        btnXacNhan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(204, 51, 255));
        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(255, 255, 255));
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jlbEmail.setForeground(new java.awt.Color(255, 0, 0));
        jlbEmail.setText("Email Không Đúng!!");

        jlbMaOTP.setForeground(new java.awt.Color(255, 0, 0));
        jlbMaOTP.setText("Mã OTP Không Đúng!!");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Mã OTP:");

        btnGuiEmail.setBackground(new java.awt.Color(204, 51, 255));
        btnGuiEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuiEmail.setForeground(new java.awt.Color(255, 255, 255));
        btnGuiEmail.setText("Gửi");
        btnGuiEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuiEmailActionPerformed(evt);
            }
        });

        txtMaOTP.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtMaOTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMaOTPKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpanelDangNhap2Layout = new javax.swing.GroupLayout(jpanelDangNhap2);
        jpanelDangNhap2.setLayout(jpanelDangNhap2Layout);
        jpanelDangNhap2Layout.setHorizontalGroup(
            jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlbEmail)
                                    .addComponent(jlbMaOTP)))
                            .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtMaOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuiEmail))))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jpanelDangNhap2Layout.setVerticalGroup(
            jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpanelDangNhap2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbEmail)
                        .addGap(24, 24, 24)
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(btnGuiEmail)
                            .addComponent(txtMaOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbMaOTP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jpanelDangNhap2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXacNhan)
                            .addComponent(btnThoat))))
                .addGap(0, 159, Short.MAX_VALUE))
        );

        getContentPane().add(jpanelDangNhap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 770, 530));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hinhNen.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 1050, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailKeyReleased

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed

        check();

        new QuenMatKhau2(null, true).ktEmail(txtEmail.getText());        // TODO add your handling code here:
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnGuiEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuiEmailActionPerformed
        if (checkMail())
            send();    // TODO add your handling code here:
    }//GEN-LAST:event_btnGuiEmailActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void txtMaOTPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMaOTPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaOTPKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuenMatKhau1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuenMatKhau1 dialog = new QuenMatKhau1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuiEmail;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jlbEmail;
    private javax.swing.JLabel jlbMaOTP;
    private com.code.db.JpanelDangNhap jpanelDangNhap2;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMaOTP;
    // End of variables declaration//GEN-END:variables
void send() {
        maOTP();
        try {
            Properties p = new Properties();
            p.put("mail.smtp.auth", "true");
            p.put("mail.smtp.starttls.enable", "true");
            p.put("mail.smtp.host", "smtp.gmail.com");
            p.put("mail.smtp.port", "587");
            p.put("mail.smtp.socketFactory.port", "587");
            p.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
            p.put("mail.smtp.ssl.protocols", "TLSv1.2");

            String accountName = "phuckemz03@gmail.com";
            String accountPasWord = "rdve bvxn dsvd sgvl";

            Session s = Session.getInstance(p, new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                    return new PasswordAuthentication(accountName, accountPasWord);
                }
            });

            String from = accountName;
            String to = txtEmail.getText();
            String subject = "Shop Thời Trang Black And White";
            String body = "Mã OTP Của Bạn Là: " + maOtp;

            Message msg = new MimeMessage(s);
            msg.setFrom(new InternetAddress(from));
            msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
            msg.setSubject(subject);
            msg.setText(body);

            Transport.send(msg);
            btnXacNhan.setEnabled(true);

            JOptionPane.showMessageDialog(this, "Đã Gửi Thành Công!!", "Thông báo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        } catch (MessagingException ex) {
            // Xử lý lỗi gửi email
            JOptionPane.showMessageDialog(this, "Lỗi Không Gửi Được!!");
            ex.printStackTrace();
        }
    }

    public void maOTP() {
        String characters = "1234567890qwertyuiopasdfghjklQWERTYUIOPASDFGHJKLZXCVBNM";
        StringBuilder sb = new StringBuilder();
        Random random = new Random();
        for (int i = 0; i < 5; i++) {
            int index = random.nextInt(characters.length());
            sb.append(characters.charAt(index));
        }
        maOtp = sb.toString();
    }

    public void check() {
        if (txtEmail.getText().isBlank()) {
            jlbEmail.setForeground(Color.red);
            jlbEmail.setText("Email không đươc để trống");
            return;
        } else {
            jlbEmail.setForeground(new Color(0, 0, 0, 0));
        }
        if (txtMaOTP.getText().isBlank()) {
            jlbMaOTP.setForeground(Color.red);
            jlbMaOTP.setText("Mã OTP không đươc để trống");
            return;
        } else {
            jlbMaOTP.setForeground(new Color(0, 0, 0, 0));
        }
        if (!checkMail()) {
            return;
        }
        if (txtMaOTP.getText().equals(maOtp)) {
            new QuenMatKhau2(null, true).email = txtEmail.getText();
            new QuenMatKhau2(null, true).setVisible(true);
            jlbMaOTP.setForeground(new Color(0, 0, 0, 0));
            dispose();
        } else {
            jlbMaOTP.setText("Mã OTP không đúng");
            jlbMaOTP.setForeground(Color.red);
            btnXacNhan.setEnabled(false);
            return;
        }

    }

    public boolean checkMail() {
        List<NhanVien> list = NhanVienDao.getAllNhanVien();
        for (NhanVien nv : list) {
            if (txtEmail.getText().equals(nv.getEmail())) {
                jlbEmail.setForeground(new Color(0, 0, 0, 0));
                return true;
            }
        }
        jlbEmail.setText("Email không tồn tại");
        jlbEmail.setForeground(Color.red);
        return false;
    }

    public String email() {
        return txtEmail.getText();
    }
}
